# Generated by Django 4.2 on 2024-02-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="date_human",
        ),
        migrations.RemoveField(
            model_name="message",
            name="negative_count",
        ),
        migrations.RemoveField(
            model_name="message",
            name="neutral_count",
        ),
        migrations.RemoveField(
            model_name="message",
            name="positive_count",
        ),
        migrations.RemoveField(
            model_name="message",
            name="score",
        ),
        migrations.AddField(
            model_name="message",
            name="channel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="telegram_bot.channel",
                verbose_name="Канал",
            ),
            preserve_default=False,
        ),
    ]
